export const ADD_CONTACT = 'ADD_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const SELECT_CONTACT = 'SELECT_CONTACT';
export const CLEAR_SELECTION = 'CLEAR_SELECTION';
export const FETCH_CONTACTS = 'FETCH_CONTACTS';
